### ISSUE TITLE
[design] Landing page

### ISSUE THREAD

**Issue by theBeginner86** [layer5io/docs#10]
#### Desired Behavior

Design and implement the landing page

#### Implementation

Refer conversation on https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?type=design&node-id=22060-14041&mode=design&t=De9vPRDsR2FLQX97-0#594925318

#### Mockups

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

**Comment by leecalcote** [comment]
![docs layer5 io](https://github.com/layer5io/docs/assets/7570704/f36b9a0f-89cd-4a9b-9748-5d2bfc794692)
