### ISSUE TITLE
Fix: Navbar's SearchBar's design is incosistent with rest of the page.

### ISSUE THREAD

**Issue by 35C4n0r** [layer5io/docs#102]
#### Current Behavior
![image](https://github.com/layer5io/docs/assets/70096901/27138d9d-ce01-4e26-95b3-fb5104cc0d18)

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by 35C4n0r** [comment]
Was this the intentional design ?

**Comment by iArchitSharma** [comment]
@35C4n0r No, i don't think so

**Comment by iArchitSharma** [comment]
Also the Active Nav Link Indicator is not working properly, it should be fixed too
![image](https://github.com/layer5io/docs/assets/74408634/62b18881-05b2-43d1-9e15-736fdfb9113b)

**Comment by iArchitSharma** [comment]
This is how search bar is supposed to look:

**Comment by iArchitSharma** [comment]
@Akshun-01 there you go

**Comment by Akshun-01** [comment]
Hey @35C4n0r where did you find this bug, after running on my local env and on the live website. None of them shows a yellow searchbar.
![image](https://github.com/layer5io/docs/assets/93793691/2ef4b7d9-32c3-410d-978c-8097fda2fb92)
This is what I can see.. 
Although it still needs some changes with respect to the proposed design that Archit mentioned, I can work on that. But I couldn't find the yellow bg color bug that you mentioned. Can you please clarify, where the issue was found.

**Comment by iArchitSharma** [comment]
@Akshun-01 yes you are right because it just got fixed with latest PR but there is still issue with **Active Nav Link** Indicator not working properly

**Comment by Akshun-01** [comment]
ok I'll see into it.

**Comment by Akshun-01** [comment]
Also @iArchitSharma , compared to the proposed design the search bar is very rounded. Does it need attention? 
![image](https://github.com/layer5io/docs/assets/93793691/0f5f5ecb-35ed-4f99-ac5b-468f7adeb095)

Like other elements on the page are also more rectangular than oval
![image](https://github.com/layer5io/docs/assets/93793691/8536ad64-5532-4a00-9f5a-cd62b3b7ced6)

**Comment by iArchitSharma** [comment]
It should be like the image below but i would suggest you to not make changes on search bar before this PR merges 
https://github.com/layer5io/docs/pull/107
![image](https://github.com/layer5io/docs/assets/74408634/02579b8e-330b-45dd-af03-bfb81c63b838)

**Comment by Raj100679** [comment]
Hey, is this issue open? I would love to work on this

**Comment by Akshun-01** [comment]
Hey, @iArchitSharma I see that PR is currently in progress. Can you please give me a ping on this when it's done? Till then I'll work on other issues. 
Thanks! ^^

**Comment by iArchitSharma** [comment]
Sure @Akshun-01 I will

**Comment by leecalcote** [comment]
Resolved. Thanks for raising this, @35C4n0r and @Akshun-01
