### ISSUE TITLE
The logos when hovered doesn't look good

### ISSUE THREAD

**Issue by Raj100679** [layer5io/docs#109]
#### Current Behavior

When we hover on meshmap docs/ night hawk docs under the tutorial section the icons should also get adjusted as dark.

#### Screenshots/Logs

https://github.com/layer5io/docs/assets/85561967/7357d680-4df5-4bbc-b928-c1b30e454594

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Raj100679** [comment]
@iArchitSharma is this issue valid?

**Comment by leecalcote** [comment]
@iArchitSharma be sure to triage, please.

@Raj100679, yes, please use the light gray or the white versions of each of the logos in SVG format. See https://layer5.io/brand.

**Comment by Raj100679** [comment]
@leecalcote Will work on it tomorrow
