### ISSUE TITLE
Add alt text to the images in docs

### ISSUE THREAD

**Issue by iArchitSharma** [layer5io/docs#116]
#### Current Behavior
**Currently, we do not have any alt text for 131 images on our site.**
![image](https://github.com/layer5io/docs/assets/74408634/f66bf343-530f-4822-b3fb-7b29df07f1fa)

#### Expected Behavior
**Please add meaningful alt text to as many images as possible.**

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by balagowda** [comment]
@iArchitSharma i would like to work on this

**Comment by surajvast1** [comment]
I would like to work on this

**Comment by ayushlohmod** [comment]
I would like to work on this. Can you please assign it to me

**Comment by iArchitSharma** [comment]
Assigning this to @surajvast1 on First come first serve basis
@ayushlohmod you can help us reviewing the PR

**Comment by surajvast1** [comment]
Hey @iArchitSharma I am glad you gave me this i am new to meshery and just finished up my setup locally can you share the link of this page whose image you have uploaded it would really help like are they images of a particular file or whole website

**Comment by nwanduka** [comment]
@iArchitSharma, could you share the link to the site containing the images that need their alt text added? The image you shared is not opening on my end. And @ surajvast1 needs the link to get started on this issue.

**Comment by iArchitSharma** [comment]
@surajvast1 @nwanduka, I don't have access to these links either. So, the only way to work on this issue is by manually inspecting the codebase or by pasting this code into the console panel to list all images without alt text of that particular page `console.table($$('img').filter(i => !i.alt), ['src'])`

**Comment by nwanduka** [comment]
Oh thanks a lot @iArchitSharma . I can view the attached image now and I think it has all the information needed to get started on the task. Thanks for also offering more clues on how to go about it. @surajvast1, you should be able to proceed now.

**Comment by surajvast1** [comment]
Thanks for assigning me this issue. I've taken the initiative to include alt tags for all the images. If there's anything else I can assist you with, please feel free to let me know—I'm here to help.

**Comment by surajvast1** [comment]
I am still working on it in parts

**Comment by surajvast1** [comment]
Thank you for assigning me the issue. I believe I have addressed most, if not all, of the images. If there are any remaining images, please feel free to leave a comment
