### ISSUE TITLE
[Home] Image escaping its container

### ISSUE THREAD

**Issue by leecalcote** [layer5io/docs#120]
#### Current Behavior
On the home page, there is a container-escaping community handbook image.

#### Expected Behavior
Image should fit to container bounds.

#### Screenshots/Logs
<img width="1902" alt="Screenshot 2023-12-28 at 9 57 44 AM" src="https://github.com/layer5io/docs/assets/7570704/6beab28e-0b0d-4f5c-a0c3-935cc825f8f3">

#### Environment

- **Host OS:** Mac 

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Excellent! Thank you, @vaibhavpnimkar

**Comment by kelvinparmar** [comment]
Hey @leecalcote This is issue is resolved or it's pending? If pending then assign to me so that I will contribute to it

**Comment by leecalcote** [comment]
@kelvinparmar thanks for volunteering. Will you review this PR? #124?
