### ISSUE TITLE
New style icon for Alert

### ISSUE THREAD

**Issue by iArchitSharma** [layer5io/docs#126]
This is how a Alert for permissions looks currently: 
![image](https://github.com/layer5io/docs/assets/74408634/f78ba52a-2b5e-4e5a-bf03-136d2b6089ac)

need to update style icon 🔐 with a new one

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by nwanduka** [comment]
Does this work? @iArchitSharma 

![Lock icon](https://github.com/layer5io/docs/assets/122698422/4a4b42cc-ed3b-4f5f-9802-132bda4e2ad3)

**Comment by iArchitSharma** [comment]
looks good to me, can you push it

**Comment by nwanduka** [comment]
Push it? As in raise a PR?
