### ISSUE TITLE
Improvement in Home Page not Responsive

### ISSUE THREAD

**Issue by Tushar-sahani** [layer5io/docs#140]
#### Current Behavior
Landing page Responsiveness breaks this is because of the  ```design your path``` button and ```dash-tangle``` shape in background and also the footer section is not perfectly align.
![Screenshot 2024-01-08 111520](https://github.com/layer5io/docs/assets/104075614/e38b46a5-7a82-4c96-b844-d35bdf510d71)
![Screenshot 2024-01-08 114833](https://github.com/layer5io/docs/assets/104075614/92c1fc61-dcc0-4c07-84ab-b24083afb279)

#### Expected Behavior
the Expected behavior should be like this.
![Screenshot 2024-01-08 114741](https://github.com/layer5io/docs/assets/104075614/02334083-79ff-429d-8e89-74c6cd416986)
![Screenshot 2024-01-08 114804](https://github.com/layer5io/docs/assets/104075614/31d518c5-d241-41b8-83ee-dc6f2d10ea51)

#### Environment

- **Mobile View or in small Screens**

**Comment by ameeetgaikwad** [comment]
Would like to work on this!

**Comment by Tushar-sahani** [comment]
@ameeetgaikwad  Yes, I will make PR soon.

**Comment by iArchitSharma** [comment]
@Tushar-sahani I would suggest wait for some time as the landing page is going through some changes
ill let you know when its done

**Comment by Tushar-sahani** [comment]
@iArchitSharma I was waiting for your reply.

**Comment by iArchitSharma** [comment]
@Tushar-sahani yes sure!

**Comment by iArchitSharma** [comment]
@Tushar-sahani how's the progress?

**Comment by Raj100679** [comment]
@iArchitSharma I would like to help here?

**Comment by Tushar-sahani** [comment]
> @Tushar-sahani how's the progress?

Currently my University Exams going on. So I will make changes till 21th January.

**Comment by Aniumbott** [comment]
Can I work on this?

**Comment by iArchitSharma** [comment]
As @Tushar-sahani has exams, let's assign this to @Aniumbott. We'll find something else for you to work on when you are back.

**Comment by Aniumbott** [comment]
@iArchitSharma the PR is already done so I think you should reassign it to @Tushar-sahani and probably close the issue.

**Comment by iArchitSharma** [comment]
oh i see
@Aniumbott Can you please help reviewing it?

**Comment by Aniumbott** [comment]
> oh i see @Aniumbott Can you please help reviewing it?

Sure
