### ISSUE TITLE
Improve Footer

### ISSUE THREAD

**Issue by theBeginner86** [layer5io/docs#15]
### Current Situation
The current footer is underwhelming at not very informative.

The content of the footer can be extended and restyled it to be consistent with the continent and footer style found on layer5.io website.

### Desired Situation
Ideally, this doc site has the exact same for the content and functionality of the layer5.io website. Improve styling by take reference (and copying) from https://gitHub.com/layer5io/layer5.

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by 35C4n0r** [comment]
@theBeginner86 i would like to work on this issue.

**Comment by abhijeetgauravm** [comment]
There u go @35C4n0r

**Comment by 35C4n0r** [comment]
@abhijeetgauravm does this look good?
![image](https://github.com/layer5io/docs/assets/70096901/8705f23b-78cf-41b2-8a0e-6ab1dfc909d5)

If this gets a ok all that will be left would be to make it responsive.
