### ISSUE TITLE
[Docs] [Reviewing Designs] Use backtick or <code> to highlight "@" keyword

### ISSUE THREAD

**Issue by leecalcote** [layer5io/docs#154]
#### Current State
The [Utilize Mentions section](https://docs.layer5.io/meshmap/designer/comments/#utilize-mentions) calls out the `@` keyword as special, but doesn't denote it as such.

#### Desired State

Use `<code>`:

> Easily draw the attention of relevant team members by tagging them in your comment. To activate this, type <code>@</code> in the comment box and a list of your team members will appear then you can select who you want to mention. This ensures that the right people are notified and can contribute to the discussion.

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Sathwik-git** [comment]
what I understand is I need to replace the text you mentioned with this one. Correct me If I am wrong
<img width="478" alt="Screenshot 2024-01-17 165657" src="https://github.com/layer5io/docs/assets/126125648/42244c61-29c2-40f9-90f8-6e89d6964c1f">

**Comment by Raj100679** [comment]
Can I work on this?

**Comment by iArchitSharma** [comment]
@Sathwik-git, please don't raise a PR without getting assigned. Anyway, now that you have raised a PR, @Raj100679, could you help review it?

**Comment by leecalcote** [comment]
> ![Screenshot (139)](https://private-user-images.githubusercontent.com/85561967/297449416-f6920dc6-3df5-46a1-943f-c3807d7aaa0d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4NzM4MDQsIm5iZiI6MTcwNTg3MzUwNCwicGF0aCI6Ii84NTU2MTk2Ny8yOTc0NDk0MTYtZjY5MjBkYzYtM2RmNS00NmExLTk0M2YtYzM4MDdkN2FhYTBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIxVDIxNDUwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmMTUwYTE1YzU4ZmNkODIzYmM3ZTQyY2ZjMWIxY2I0ZmM3MDIzOWMzNWQyYjgzOWM4OTQ1NDE4MTQyZmQ4MTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xCtdsmInRXuc-CdPJGv-uBPJV7ZXHAwQpecCv__hIxs) ![Screenshot (140)](https://private-user-images.githubusercontent.com/85561967/297449507-b78a4761-17d8-40ec-9342-16601c6fea7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4NzM4MDQsIm5iZiI6MTcwNTg3MzUwNCwicGF0aCI6Ii84NTU2MTk2Ny8yOTc0NDk1MDctYjc4YTQ3NjEtMTdkOC00MGVjLTkzNDItMTY2MDFjNmZlYTdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIxVDIxNDUwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3Y2NkZDI0ZTBkMWZmNTczNDM5OGI5MDNkMTE5MjcxNjkxMDFkNmFjN2E1MjY3NDkzMGFjYjhkNDA3OGMyNjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UmKOMnBRKUV9gtqbDsIg4C7hdWAoIctIhP14GBARoCk) @leecalcote @iArchitSharma What should we proceed with `` or `` ? ``

@Raj100679  Yes, do it. Also, confirm the `<code>` colorizes (highlights) the tagged text.

**Comment by leecalcote** [comment]
Multiple attempts from multiple contributors... I must not have described this well. Let's close this. Entirely too much work for such a simple thing

**Comment by leecalcote** [comment]
I give up.
