### ISSUE TITLE
[Docs] LOCAL SETUP : building docker image 

### ISSUE THREAD

**Issue by Sathwik-git** [layer5io/docs#161]
#### Current State

<img width="628" alt="Screenshot 2024-01-21 115051" src="https://github.com/layer5io/docs/assets/126125648/2db43953-05c1-4ae7-8caf-324b8f706f6f">

When used command "run docker" it does not build the image. Here's what it's saying 
<img width="518" alt="Screenshot 2024-01-21 115217" src="https://github.com/layer5io/docs/assets/126125648/9972addc-5fba-4363-9745-f05b4796457f">
 
#### Desired State

It needs to build the docker image 
---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Thanks for raising this issue. This is a valid bug.

**Comment by Nabanita29** [comment]
I can work on this if available!
