### ISSUE TITLE
[Docs] Enhancement to global <title> tag

### ISSUE THREAD

**Issue by leecalcote** [layer5io/docs#163]
### Current State
Each page specific title is included in the `<title>` tag, however after the pipe `|` the "Layer5" word is missing.

### Desired State
![Untitled](https://github.com/layer5io/docs/assets/7570704/c566a799-b2ed-49ca-b812-f5f421d978f8)

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by nikhilkalburgi** [comment]
Hi @leecalcote,
I can take this task. In fact, have a solution ready here.

**We need to include head.html and override docsy head theme and add the text "Layer5" after pipe**

Update in **head.html**:
```
<title>
  {{- if .IsHome -}}
    {{ .Site.Title -}}
  {{ else -}}
    {{ with .Title }}{{ . }} | Layer5{{ end -}}
    {{ .Site.Title -}}
  {{ end -}}
</title>
```

Result:
![image](https://github.com/layer5io/docs/assets/70331875/5c1c6896-94a3-499f-a9c5-cd1056b6b51a)

**Comment by nikhilkalburgi** [comment]
Hi @leecalcote,

Can I implement the above solution and raise a PR?
