### ISSUE TITLE
[Docs] Products Dropdown Issue

### ISSUE THREAD

**Issue by nikhilkalburgi** [layer5io/docs#166]
#### Current State
1. The Dropdown is not disappearing when clicked on other portion of the site
2. When clicked on Products the page scrolls to top
3. The dropdown hides behind the footer when scrolled to bottom

https://github.com/layer5io/docs/assets/70331875/5aacda9f-3196-4369-b938-0d71ad42acc3

#### Desired State
The above problem should be resolved

#### Willing to take this task?
Yes

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Nabanita29** [comment]
hii I can work on this!
