### ISSUE TITLE
[Docs] New feature: Silencing Comment Notifications

### ISSUE THREAD

**Issue by leecalcote** [layer5io/docs#169]
#### Current State
This new feature needs to be documented.

<img width="520" alt="Screenshot 2024-01-23 at 10 54 37 AM" src="https://github.com/layer5io/docs/assets/7570704/7f6c4b2d-4061-4b44-ae70-79a5250e8c7d">

Find this feature in the Comment component in MeshMap.

#### Desired State
Add a description of the behavior of this feature to the existing design reviews page.
Add any suggestions to "Best Practices for Effective Design Reviews" section, too.
Also, update the user notification preferences description (page) as needed.

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@captain-Akshay @nwanduka is this item already completed? I _think_ that it is.

**Comment by nwanduka** [comment]
> @captain-Akshay @nwanduka is this item already completed? I _think_ that it is.

Yes, it has been completed.

https://docs.layer5.io/meshmap/designer/comments/#mute-comment-notifications
