### ISSUE TITLE
[Feature] Mobile menu

### ISSUE THREAD

**Issue by leecalcote** [layer5io/docs#19]
#### Current Behavior
This docs doesn’t have a mobile menu for visitors trying to read documentation on their mobile devices.

#### Implementation
identify whether or not there is a mobile friendly menu available from the Docsy.dev theme. Enable it and reuse it if so.

If one is not available from docsy theme, search for commonly used mobile menus on other Hugo teams or projects. 

#### Mockup

<img width="1295" alt="Screenshot 2023-10-28 at 2 26 57 PM" src="https://github.com/layer5io/docs/assets/7570704/10a11288-ab3f-47d0-acaa-feaac09dbdf5">

---

**[Contributor Guide](https://docs.meshery.io/project/contributing)**
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

**Comment by Wise-Wizard** [comment]
Hi @leecalcote, I would like to work on this issue!

**Comment by leecalcote** [comment]
Thanks. Have you worked with Hugo sites before, @Wise-Wizard?

It turns out that there is a menu, I just couldn't see it on my iPhone. Maybe it is the coloring of the hamburger menu I'm not sure. Having said that, we do need an enhanced menu that looks like the mockup.

**Comment by abhijeetgauravm** [comment]
@Wise-Wizard any updates here?

**Comment by preyanshu** [comment]
hiiii @leecalcote can i work on this ?

**Comment by leecalcote** [comment]
Thanks for asking, @preyanshu. 

@iArchitSharma Will you make an assessment as whether or not this issue is still valid or has already been taken care of?

**Comment by iArchitSharma** [comment]
We already have a mobile-friendly site, so we can close this issue:
![image](https://github.com/layer5io/docs/assets/74408634/9ed7bd3f-355b-40ba-ae4e-2907e0abacae)
