### ISSUE TITLE
[Docs] "warning" is inappropriate

### ISSUE THREAD

**Issue by hamza-mohd** [layer5io/docs#190]
#### Current Behavior
On https://docs.layer5.io/cloud/reference/#all-api-endpoints

#### Expected Behavior
This note is informational and should not be a warning.

#### Screenshots/Logs

<img width="865" alt="Screenshot 2024-01-26 at 1 10 09 PM" src="https://github.com/layer5io/docs/assets/135669921/0e2a7782-3fa1-4fd6-8d22-c0486bf63c8b">

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by nikhilkalburgi** [comment]
Hi @hamza-mohd ,

Are you expecting this?
![image](https://github.com/layer5io/docs/assets/70331875/d2bef787-61d2-4399-9970-f90aea8d6aa9)

If **yes** and if this Issue is **open** then can I raise a PR?

**Comment by iArchitSharma** [comment]
Thanks for listing this issue @hamza-mohd ,
@nikhilkalburgi go on please raise the PR

**Comment by iArchitSharma** [comment]
@nikhilkalburgi are you still fixing this?

**Comment by nikhilkalburgi** [comment]
Yes, I will raise the PR by tomorrow
