### ISSUE TITLE
[Extensions] Rendering Failing dues to edge styles

### ISSUE THREAD

**Issue by aabidsofi19** [layer5io/docs#203]
<@U05U2487R4Z> Rendering Failing for edges :

[Slack Message](https://layer5io.slack.com/archives/G01BD9056TD/p1706962420631809)

**Comment by leecalcote** [comment]
@captain-Akshay working on this?

**Comment by captain-Akshay** [comment]
yes! but i was not able to reproduce it 
@aabidsofi19 it would be great if you could share the link of the design to work with
