### ISSUE TITLE
[Grammar Adjustment] Tutorials - MeshMap Snapshots

### ISSUE THREAD

**Issue by sandramsc** [layer5io/docs#208]
**Current State:**

- Link to website: [MeshMap Snapshot](https://docs.layer5.io/cloud/tutorials/gitops-snapshots/)
- Currently, the text in the sentences below have some grammar or spelling errors.
![l5](https://github.com/layer5io/docs/assets/19821445/8d356d7a-32ca-4120-a95a-1c76c081fb98)

**Desired State:**
3. Use the multi-step connection wizard to authorize Meshery to access your GitHub repositories (you may need to sign into GitHub).
6. You will establish a secret for the Meshery GitHub app and a new workflow to be invoked when a new snapshot is needed.
6.1 Customize the workflow on event trigger to match your needs. 

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by sandramsc** [comment]
**Discuss:** It could be that the word **on** in point 6.1 is in the current format because its purpose is to convey a state (i.e inside a code block)

**Comment by PersonaMate** [comment]
Hey @sandramsc, I am new to the community and would like to work on this simple issue.

**Comment by sandramsc** [comment]
@PersonaMate Welcome to the community, I have assigned this to you.

**Comment by PersonaMate** [comment]
@sandramsc, 

Discuss:

It could be that the word on in point 6.1 is in the current format because its purpose is to convey a state (i.e. inside a code block)

..... So should I leave it as it is or make it normal? (For 6.1)

**Comment by leecalcote** [comment]
Bump

**Comment by sandramsc** [comment]
@vishalvivekm Hi, what's your view on this on this one?

**Comment by Ashparshp** [comment]
@PersonaMate, any progress on this?
