### ISSUE TITLE
[Grammar Adjustment] Tutorials - Self-Hosted

### ISSUE THREAD

**Issue by sandramsc** [layer5io/docs#209]
**Current State:**

- Link to website: [MeshMap Snapshot](https://docs.layer5.io/cloud/tutorials/gitops-snapshots/)
- Currently, the heading in the alert section reads as follows: As as Service
![m](https://github.com/layer5io/docs/assets/19821445/7407138a-9dc6-4cdf-9506-469fdb156d3d)

**Desired State:**
Suggested change: As a Service

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Raj100679** [comment]
@sandramsc Can you assign this to me?

**Comment by sandramsc** [comment]
Hi @Raj100679 Thanks for your enthusiasm to work on the issue, I see you already created a PR, please wait for the issue to be assigned before making the commitment of submitting a solution via PR. If you haven't already please read the CONTRIBUTING.md on issue assignment.

Since you were the first to comment, I'll go ahead and assign it to you.
