### ISSUE TITLE
[Docs]

### ISSUE THREAD

**Issue by deining** [layer5io/docs#217]
#### Current State
There are various typos present in `assets/csv/keys.csv`:

```
./assets/csv/keys.csv:5: Pasword ==> Password
./assets/csv/keys.csv:9: Subcription ==> Subscription
./assets/csv/keys.csv:272: Platfrom ==> Platform
./assets/csv/keys.csv:273: Platfrom ==> Platform
./assets/csv/keys.csv:274: Platfrom ==> Platform
./assets/csv/keys.csv:275: Platfrom ==> Platform
./assets/csv/keys.csv:276: Platfrom ==> Platform
./assets/csv/keys.csv:304: Registation ==> Registration
./assets/csv/keys.csv:310: Platfrom ==> Platform
./assets/csv/keys.csv:318: confuguration ==> configuration
./assets/csv/keys.csv:342: performace ==> performance
./assets/csv/keys.csv:343: offical ==> official
./assets/csv/keys.csv:380: mutli ==> multi
./assets/csv/keys.csv:382: performace ==> performance
./assets/csv/keys.csv:382: performace ==> performance
./assets/csv/keys.csv:382: Platfrom ==> Platform
./assets/csv/keys.csv:382: performace ==> performance
./assets/csv/keys.csv:382: performace ==> performance
./assets/csv/keys.csv:383: Platfrom ==> Platform
```
#### Desired State

These typos should be eliminated.

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@deining, I completely missed this. Thank you very much for this.

@iArchitSharma, have you messaged with @deining? Let's be sure to encourage him to undertake this fix, if he'd like to.

@deining, would you like to take assignment of this issue?

**Comment by psankhe28** [comment]
@deining If you are not working on this, can I take up this?

**Comment by deining** [comment]
> @deining If you are not working on this, can I take up this?

Sure, go ahead!
