### ISSUE TITLE
[Docs] New Section or Page: Starting from a Helm Chart

### ISSUE THREAD

**Issue by leecalcote** [layer5io/docs#236]
#### Current State
Similar to the page for [creating a design from scratch](https://docs.layer5.io/meshmap/getting-started/starting-scratch/), the MeshMap docs are in need of a new page that describes "creating a design from Helm Chart"

#### Desired State

A new page that walks users through this process.

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by UncleWeeds** [comment]
@leecalcote, Hey I am new to the community and have quite a bit of experience in the tech stacks mentioned above, would love to help on this issue.

**Comment by leecalcote** [comment]
@UncleWeeds, great. How is your other assigned issue coming along?

**Comment by UncleWeeds** [comment]
@leecalcote, Haha gonna be honest, I am still playing around with meshery and probably would do it for a few more days before I start working on it. But ya I will surely try my best to help the community out tho, also enjoyed yesterday's meeting.
