### ISSUE TITLE
[Bug]: Some pages on documentation are breaking in mobile view. 

### ISSUE THREAD

**Issue by Haimantika** [layer5io/docs#238]
#### Current Behavior

The pre-requisites part is breaking in mobile view. I noticed it [here](https://docs.meshery.io/installation/kubernetes/helm) and in other installation guides as well. 

#### Expected Behavior
The text is going beyond the box, ideally it should be within the box. 

#### Screenshots/Logs
![IMG_2213](https://github.com/layer5io/docs/assets/32809211/c23635f5-8cbe-4a65-b0d8-ae824f05d353)

#### Environment
Found this in Chrome browser.

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by iArchitSharma** [comment]
@Haimantika, thanks for raising the issue, but you've posted it in the wrong repository. This repository is for docs.layer5.io, not docs.meshery.io
