### ISSUE TITLE
Ensure that opengraph images are available for each docs page

### ISSUE THREAD

**Issue by leecalcote** [layer5io/docs#243]
#### Current Behavior
See this example of a missing image - https://twitter.com/layer5/status/1782612959094624636

<img width="594" alt="Screenshot 2024-04-22 at 10 34 50 PM" src="https://github.com/layer5io/docs/assets/7570704/cfbd1584-0156-4902-8d95-20d16615e98e">

#### Desired Behavior
1. A general and generic branded Layer5 image - same as that used on layer5.io.
1. A specific image where appropriate (if at all) for specific docs pages.

#### Implementation
Reuse opengraph image from layer5.io site.

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

**Comment by iArchitSharma** [comment]
Fixed
