### ISSUE TITLE
[Site] Convert nav link to external link

### ISSUE THREAD

**Issue by leecalcote** [layer5io/docs#26]
#### Current Behavior
The Playground link opens a page on docs.layer5.io.

#### Desired Behavior
Change the Playground link to open https://play.meshery.io instead.

#### Mockups
<img width="490" alt="Screenshot 2023-10-29 at 7 13 57 PM" src="https://github.com/meshery/meshery/assets/7570704/9ff0ea55-a5aa-412b-a20f-8838304b5122">

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

**Comment by Jat1nSood** [comment]
@leecalcote  Please Assign this to me

**Comment by leecalcote** [comment]
Thanks for volunteering, @Jat1nSood. Yes, will you confirm the specifics of your approach to a  fix?

**Comment by Jat1nSood** [comment]
@leecalcote although, I am not familiar with hugo but I tried and after  going through the documentation and some tutorials I tried to solve the issue. One error is there that which says URLs with protocol  http* are not supported . I looked and found one option i.e. to set uglyURLs = true in config.toml . It did'nt work. Also tried to add link to shortcode directory but nothing worked. I will look more.

**Comment by hemantmm** [comment]
Hi, @leecalcote like the playground is not visible on the page 
![Screenshot 2023-11-01 205928](https://github.com/layer5io/docs/assets/92446645/93fe6b28-54c4-46f0-9b63-21fb44819c15)

Should I add the Playground in the navbar?

**Comment by leecalcote** [comment]
@hemantmm, yes, I removed it since it doesn't redirect currently.

**Comment by hemantmm** [comment]
@leecalcote, Should I include that Playground in the navbar with the correct link provided above?

**Comment by leecalcote** [comment]
That's what this issue calls for, yes.

**Comment by roshil1206** [comment]
I would like to work on it

**Comment by 35C4n0r** [comment]
@leecalcote i've got this figured out, kindly assign the issue to me.

**Comment by leecalcote** [comment]
@roshil1206 I'm sorry to have missed your message earlier.

@35C4n0r, just as you jump in here, ping @Modern-artist (Prem Kumar in Slack) about the menu mockup that he has for this nav bar. Speaking of nav bar, we'll want for the logo and menu to be sticky and the page content to scroll underneath.

**Comment by leecalcote** [comment]
We might want to simply reuse the mega menu from layer5io/layer5.

**Comment by 35C4n0r** [comment]
I'm not able to seem Prem Kumar on the slack anymore neither any mockups for the navbar here https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?node-id=21084%3A6224&mode=dev

**Comment by 35C4n0r** [comment]
> We might want to simply reuse the mega menu from layer5io/layer5.

Do we want to include all the images too ?
![image](https://github.com/layer5io/docs/assets/70096901/b1a122be-292d-4e72-b2f2-86386201b120)
