### ISSUE TITLE
[CI] Update Docsy to v0.10

### ISSUE THREAD

**Issue by dragon-slayer875** [layer5io/docs#260]
#### Current Behavior

While updating Docsy, the site has many changes, including colors, etc, which are not intended.

#### Desired Behavior

Docsy has released v0.10 on May2, 2024 with some changes that deviate our themes from their original intent.
Care should be taken while updating it, and required changes and subsequent reviews should be made to make sure the site layout stays intact.

#### Acceptance Tests

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by dragon-slayer875** [comment]
// @leecalcote

**Comment by leecalcote** [comment]
@Archit Sharma please carry this forward.

**Comment by leecalcote** [comment]
There is an open PR with part of the work complete - #263
