### ISSUE TITLE
[Docs] Self-Hosted: Responsiveness of Helm values table 

### ISSUE THREAD

**Issue by leecalcote** [layer5io/docs#269]
#### Current Behavior
The table on this page overflows and is difficult to read - http://localhost:1313/cloud/self-hosted/helm-chart-values/

#### Expected Behavior
The table shouldn't expand past the container and the words and values inside the table sells should line wrap.

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by GaganpreetKaurKalsi** [comment]
Hey Lee, how can I access this page? It's giving page-not-found at the provided url


![image](https://github.com/layer5io/docs/assets/54144759/e8042829-8a32-426a-a880-b4ed2a9ec3b6)

**Comment by iArchitSharma** [comment]
@GaganpreetKaurKalsi hey actually he meant this page - https://docs.layer5.io/cloud/self-hosted/deployment/helm-chart-values/

**Comment by Rishikesh63** [comment]
@iArchitSharma  i would like to work on this issue please can you assign to me

**Comment by GaganpreetKaurKalsi** [comment]
Got it @iArchitSharma 👍 I should have explored its nested routes as well.

**Comment by GaganpreetKaurKalsi** [comment]
Hey @Rishikesh63, any progress on this issue?

**Comment by Rishikesh63** [comment]
![image](https://github.com/layer5io/docs/assets/130288820/429450ba-04db-478a-b1e1-a8d1cc8f7cfb)

can i wrap all values in a table

**Comment by iArchitSharma** [comment]
@Rishikesh63 no please its already a table and we want to use the same design, just make the table scrollable instead of whole page

**Comment by Rishikesh63** [comment]
@iArchitSharma  can you please review and merge my PR ?
