### ISSUE TITLE
[Cloud] Catalog: Description of content metrics

### ISSUE THREAD

**Issue by leecalcote** [layer5io/docs#275]
#### Desired State

A new page or new section on the Cloud Catalog, describing metrics: what they mean, how they are measured, when the are refreshed.

[Slack Message](https://layer5io.slack.com/archives/G019GNQGPL4/p1718038874761639?thread_ts=1718038673.408469&cid=G019GNQGPL4)

**Comment by jameshorton2337** [comment]
@iArchitSharma, you said there is an existing page for this, right? https://docs.layer5.io/cloud/catalog/

I don't see any information about metrics or leaderboard. // @leecalcote @captain-Akshay

**Comment by jameshorton2337** [comment]
Is help needed here?

**Comment by iArchitSharma** [comment]
@jameshorton2337 ill let you know if i need help, thanks!
