### ISSUE TITLE
Unable to scroll through left sidebar

### ISSUE THREAD

**Issue by GaganpreetKaurKalsi** [layer5io/docs#278]
#### Current Behavior
Unable to access nav links due to absence of scrollbar in left sidebar

<img width="400" alt="image" src="https://github.com/layer5io/docs/assets/54144759/e8f33ab2-28a3-408d-95c4-b3b62ead028c">

<br><br>

Also there is this scrollbar at the bottom which needs to be fixed, happens to come only on cloud page

<img width="400" alt="image" src="https://github.com/layer5io/docs/assets/54144759/8cdd25b9-4fea-4697-92c3-cec75d1454e7">

#### Expected Behavior
A scrollbar to be able to navigate through all links

<img width="400" alt="image" src="https://github.com/layer5io/docs/assets/54144759/906eecfb-8877-469f-8362-59b335e0b281">

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by iArchitSharma** [comment]
@GaganpreetKaurKalsi Thanks for bringing this up

**Comment by Rishikesh63** [comment]
i would like to workon this issue

**Comment by preyanshu** [comment]
hii i would like to work on this

**Comment by Ashparshp** [comment]
As we discussed, I am going to assign it to @preyanshu. I hope there's no problem @Rishikesh63, right?
