### ISSUE TITLE
Text not visible inside Table

### ISSUE THREAD

**Issue by GaganpreetKaurKalsi** [layer5io/docs#279]
#### Current Behavior

Text in Table not visible on https://docs.layer5.io/cloud/identity/users/default-permissions/

![image](https://github.com/layer5io/docs/assets/54144759/3e431eb4-2610-450b-bc74-261619aafb08)

#### Expected Behavior
Should be visible

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Thank you! Help wanted. 👍

**Comment by Ashparshp** [comment]
@Aviral0702 Sure, go ahead!

**Comment by 2003Aditya** [comment]
> @Ashparshp Thanks! Starting to work on it.

Are you still working on this issue?

**Comment by leecalcote** [comment]
@Aviral0702 ready to let another contributor take a crack at this one or will you have this completed no later than today?
