### ISSUE TITLE
UI issues with Tokens placeholder

### ISSUE THREAD

**Issue by GaganpreetKaurKalsi** [layer5io/docs#280]
#### Current Behavior
- Placeholder for token empty
- Hover state of copy button looks weird
- The tooltip over copy button not visible
<img width="959" alt="image" src="https://github.com/layer5io/docs/assets/54144759/15a91550-07b5-44f1-9b20-001bb0907f16">

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by GaganpreetKaurKalsi** [comment]
Same button UI and tooltip issue on https://docs.layer5.io/cloud/self-hosted/customizing-webhooks/ along with a thick x-axis scrollbar.


![image](https://github.com/layer5io/docs/assets/54144759/f5b7ee9d-8e99-48c9-ac8b-b84ff7d71767)

**Comment by preyanshu** [comment]
Hi @Ashparshp can i work on this one ? I have already worked on the same page regarding the issue of the side navbar not scrolling

**Comment by Ashparshp** [comment]
@GaganpreetKaurKalsi, could I assign this to @preyanshu?

**Comment by GaganpreetKaurKalsi** [comment]
@vishalvivekm could you help set expectations for this issue?

**Comment by iArchitSharma** [comment]
Thanks for bringing this up, @GaganpreetKaurKalsi. We recently upgraded to the new Docsy version - https://github.com/layer5io/docs/pull/263. This brought some unexpected UI changes related to colors. I've fixed most of them, but I didn't notice this one. Would you like to work on it?

**Comment by GaganpreetKaurKalsi** [comment]
Sure @iArchitSharma. Let me know what content should be there in the token placeholder.

**Comment by iArchitSharma** [comment]
Misunderstanding on my part; I thought it was a color issue, but the content is missing. Let me confirm this with the cloud maintainers.

@GaganpreetKaurKalsi

**Comment by GaganpreetKaurKalsi** [comment]
Thanks @iArchitSharma
