### ISSUE TITLE
Alignment issue in navbar

### ISSUE THREAD

**Issue by GaganpreetKaurKalsi** [layer5io/docs#284]
#### Current Behavior

nav-items aren't aligned with the brand logo for screen width<990px

<img width="629" alt="image" src="https://github.com/layer5io/docs/assets/54144759/9b8eadb7-fb5f-4158-987b-e4eaaf23b3c4">

#### Expected Behavior
nav elements should be aligned with the logo

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by hargunkaur286** [comment]
Can I work on this issue? @GaganpreetKaurKalsi
