### ISSUE TITLE
[Feat]: Improvement in footer when width is smaller 

### ISSUE THREAD

**Issue by upsaurav12** [layer5io/docs#286]
#### Current Behavior
Currently the of the page is looking like this
![image](https://github.com/layer5io/docs/assets/116784047/b4d3bba7-90df-473a-9e8e-21bb85daed81)
so the problem in this when the width size is smaller some containers like ``resources`` and ``community`` breaking especially in mobile version with the width of below ``400px``

#### Desired Behavior
I think there are 2 solutions:-
1. To make them in same level below 400px 
2. To make all the conta.iner in different level like resources , community , solution and then company. 

For my POV 2 could be better option because in 1st approach there are chances that the same error will show but in different ``breakpoint`` or different width.

#### Mockups

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

**Comment by hargunkaur286** [comment]
Can I work on this issue? @upsaurav12

**Comment by upsaurav12** [comment]
I want to work on this issue just waiting for maintainer to assign me

**Comment by Ashparshp** [comment]
@upsaurav12 Thanks for opening the issue! It seems this problem can be fixed. @hargunkaur286, any objections if we assign this to Saurav? Hope that's okay with you. By the way, before we proceed, are there really smartphones in the market with a width less than 309px? I don't think so!

**Comment by upsaurav12** [comment]
I tried to find some some smartphone but mostly they are ``350px >=`` and  ``<400px`` including s20 , iphone11 , iphone12 etc but i actually found a smartphone which is nokia 8110 4G which is ``240px`` but i dont think many are using using this phone 
![image](https://github.com/layer5io/docs/assets/116784047/477dfc51-700f-430c-8c8a-4c26e6364bec)
You can also verify this also

**Comment by Ashparshp** [comment]
@upsaurav12 Alright! Assigned to you! Go ahead.

**Comment by upsaurav12** [comment]
Thank you

**Comment by upsaurav12** [comment]
Hi @Ashparshp i was looking for solution for this issue but i got this 
![image](https://github.com/layer5io/docs/assets/116784047/02829e2a-6689-415d-b0e9-aff660b28b90)
the company container is also breaking between ``850px <= and 800px>`` can we look to this also ???

**Comment by Ashparshp** [comment]
It's breaking at multiple places, like between 700px and 800px. Take your time to test it thoroughly, fix all the issues, and ensure everything works correctly after fixing.

**Comment by upsaurav12** [comment]
![image](https://github.com/layer5io/docs/assets/116784047/38b0a75a-2ddb-4fde-874b-60e6ca34ee1c)
i got this the ``odd-col`` and ``even-col`` are breaking that were vertically aligned after it so i think we need to look at this
