### ISSUE TITLE
[Docs] Workspace Manager and Workspace Admin Roles

### ISSUE THREAD

**Issue by leecalcote** [layer5io/docs#297]
#### Current State
Two new roles have become available as of Cloud v0.7.176.

#### Desired State
Both of these roles, their purpose, and their default permissions are documented.

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Yashsharma1911** [comment]
> @Yashsharma1911 are these permissions being published?

For user role yes, for workspace manager and admin no, it will require small change to publish these too @dragon-slayer875
