### ISSUE TITLE
Workflow adds unwanted first line in csv

### ISSUE THREAD

**Issue by iArchitSharma** [layer5io/docs#305]
#### Current Behavior
First line in green is an unwanted row, being added by the workflow used for fetching this data
![image_720](https://github.com/layer5io/docs/assets/74408634/0dcc8a82-a03d-451b-b784-c136230ca1b6)

The workflow is - https://github.com/layer5io/docs/blob/master/.github/workflows/generate-keys.yml

#### Expected Behavior
the first row, should not be fetched,
![image](https://github.com/layer5io/docs/assets/74408634/83b739f1-9caa-4559-954c-0bb88b5b5055)

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Has this been taken care of @iArchitSharma?

**Comment by Yashsharma1911** [comment]
Yes Lee, this issue is taken care of in this PR - https://github.com/layer5io/docs/pull/318

I'm closing this issue
