### ISSUE TITLE
Dropdown in Navbar Not Visible on Hover

### ISSUE THREAD

**Issue by Ashparshp** [layer5io/docs#308]
#### Current Behavior
On the [docs.layer5.io](https://docs.layer5.io/) website, the dropdown in the navbar for "Products" isn't visible when hovered over; it only works on click.

#### Expected Behavior
The dropdown menu should be visible when the "Products" option in the navbar is hovered over.

#### Screenshots/Logs
![Screenshot (12)](https://github.com/layer5io/docs/assets/150526286/faba22f8-d9d6-4ff3-84c6-86208dbbdbab)

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by ConradKash** [comment]
Can you assign this to me.
