### ISSUE TITLE
[Docs] Hyperlink each Role name from Permissions Reference page to Roles page

### ISSUE THREAD

**Issue by jameshorton2337** [layer5io/docs#321]
#### Current State
This page lists permissions for each role, but doesn't offer a link to each role description - https://docs.layer5.io/cloud/reference/default-permissions/

#### Desired State
Hyperlink each Role name from Permissions Reference page to Roles page

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@dragon-slayer875

**Comment by leecalcote** [comment]
Not @dragon-slayer875 😢

**Comment by SAHU-01** [comment]
May I work on this?

**Comment by iushdoescode** [comment]
Hi lee,
I would like to work on the issue.
 Could you please assign this task to me?
Thank you!

**Comment by SAHU-01** [comment]
@leecalcote and @jameshorton2337 a quick clarification here,
Let's say to hyperlink `Workspace Admin` role in the column which link should I use?

1. https://docs.layer5.io/cloud/security/roles/workspace-roles/ or
2. https://docs.layer5.io/cloud/security/roles/#workspace-roles

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/ab2a9339-60a3-4114-8fe2-743d3df36ead">

**Comment by dragon-slayer875** [comment]
> @leecalcote and @jameshorton2337 a quick clarification here, Let's say to hyperlink `Workspace Admin` role in the column which link should I use?
> 
> 1. https://docs.layer5.io/cloud/security/roles/workspace-roles/ or
> 2. https://docs.layer5.io/cloud/security/roles/#workspace-roles
> 
> <img alt="image" width="1512" src="https://private-user-images.githubusercontent.com/71656941/350707773-ab2a9339-60a3-4114-8fe2-743d3df36ead.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0OTY0MTAsIm5iZiI6MTcyMTQ5NjExMCwicGF0aCI6Ii83MTY1Njk0MS8zNTA3MDc3NzMtYWIyYTkzMzktNjBhMy00MTE0LThmZTItNzQzZDNkZjM2ZWFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIwVDE3MjE1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmZTc4NmJiZDE4YTU1MzhmYmFlZjM1MjJkMjU4NzM3ZWI4N2M1MWQ3YWE3YTIzYjJhYjk5MmFmYzY2NGM4MjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-rIjUTCf04bpOkCOd2yMsDvYPkYQhGCZAbdaqB9Gg8s">

https://docs.layer5.io/cloud/security/roles/workspace-roles/

**Comment by SAHU-01** [comment]
@dragon-slayer875 for `user` which hyperlink should I use? I mapped the rest but couldn't figure out what would be best for `user`

**Comment by dragon-slayer875** [comment]
Ah. We are missing a page for the user role. You can raise a PR in the meantime, I will see to it that it is added by tomorrow.

**Comment by SAHU-01** [comment]
@leecalcote and @dragon-slayer875 is this the desired functionality?

https://github.com/user-attachments/assets/84a675d6-7d01-4268-afcb-74bdf3aad5aa

or should clicking the role name open the hyperlink in a new tab like this?

https://github.com/user-attachments/assets/b34ce234-816a-4ddc-8b4a-73e713529b55

**Comment by dragon-slayer875** [comment]
> @leecalcote and @dragon-slayer875 is this the desired functionality?
> 
>  option1.mov 
> or should clicking the role name open the hyperlink in a new tab like this?
> 
>  option2.mov

Opening the link in a new tab makes sense to me since people will be able to read the descriptions and understand them in reference to the permissions table side by side.

**Comment by leecalcote** [comment]
> > @leecalcote and @dragon-slayer875 is this the desired functionality?
> > option1.mov
> > or should clicking the role name open the hyperlink in a new tab like this?
> > option2.mov
> 
> Opening the link in a new tab makes sense to me since people will be able to read the descriptions and understand them in reference to the permissions table side by side.

Let's stick with only targeting a new window/tab for links external to the site. Otherwise, all links under docs.layer5.io should open in the same window.
