### ISSUE TITLE
[Docs] Permissions by Role

### ISSUE THREAD

**Issue by leecalcote** [layer5io/docs#323]
#### Current State
https://docs.layer5.io/cloud/reference/default-permissions/

#### Desired State
Present the permissions table in Layer5 docs in an alternative format not categorized by Function / Keychain, but by role.

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@dragon-slayer875 @Yashsharma1911 progress?

**Comment by leecalcote** [comment]
This can be accomplished using the existing spreadsheet that is available in the repo already, right?

**Comment by dragon-slayer875** [comment]
Raised PR. 

> This can be accomplished using the existing spreadsheet that is available in the repo already, right?

Apologies. Was helping family over Sunday.
The task itself wasn't a problem.
Raised PR.
