### ISSUE TITLE
Change hyperlink for "Create docs issue" to reference issue template

### ISSUE THREAD

**Issue by leecalcote** [layer5io/docs#333]
#### Current Behavior
The hyperlink under this text open a new, blank issue that is missing helpful information contained in the docs issue template.

![Screenshot 2024-07-26 at 3 39 09 PM](https://github.com/user-attachments/assets/2375b6c7-2938-43f0-a7c2-20ac8a04d55c)

#### Desired Behavior
Point to this issue template instead - https://github.com/layer5io/docs/issues/new?assignees=&labels=area%2Fdocs%2C+framework%2Fhugo%2C+language%2Fmarkdown&projects=&template=documentation.md&title=%5BDocs%5D

---

#### Contributor Guide and Resources
- 📚 [Instructions for contributing to documentation](https://github.com/layer5io/docs/blob/master/CONTRIBUTING.md)
   - Layer5 documentation [site](https://docs.layer5.io) and [source](https://github.com/layer5io/docs/)
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by viv511** [comment]
Hi! I'd like to help with this!

@viv511
