### ISSUE TITLE
[Docs]update  CODE_OF_CONDUCT.md  

### ISSUE THREAD

**Issue by Swarnim114** [layer5io/docs#339]
## Enhance Code of Conduct
The current CODE_OF_CONDUCT.md file requires updates to better reflect our community standards. This pull request aims to improve the code of conduct, ensuring a more inclusive and respectful environment for all contributors.

### Expected Changes

    Revise the code of conduct to align with industry best practices
    Clarify expectations for behavior and communication
    Add or remove sections as necessary to ensure comprehensive coverage

Reference
Please review the current CODE_OF_CONDUCT.md file: 
![image](https://github.com/user-attachments/assets/bdba10d7-d86b-4b30-9eec-2b2f5598a767)

**Comment by Swarnim114** [comment]
@hargunkaur286  I would like to work on this issue.

**Comment by leecalcote** [comment]
Thanks, @Swarnim114. Which aspect of the CNCF Code of Conduct doesn't cover the items in "Expected Changes"?

**Comment by sudhanshutech** [comment]
@Swarnim114 please if you would provide response for the question asked above?
