### ISSUE TITLE
[Docs] GitHub workflow guide - Page not found

### ISSUE THREAD

**Issue by Aviral0702** [layer5io/docs#340]
#### Current State  
The "guide to a standard GitHub workflow" link under Quickstart on this [page](https://docs.layer5.io/meshmap/reference/contributing-to-docs/) leads to a 404 error.  

![image](https://github.com/user-attachments/assets/81841d78-243f-462d-823f-f1eb38adc163)  

#### Desired State  
The link should redirect to: https://github.com/layer5io/docs/blob/master/CONTRIBUTING-gitflow.md  

---  

#### Contributor Guide and Resources  
- 📚 [Instructions for contributing to documentation](https://github.com/layer5io/docs/blob/master/CONTRIBUTING.md)  
   - Visit the Layer5 documentation [site](https://docs.layer5.io) and [source](https://github.com/layer5io/docs/)  
- 🎨 Access wireframes and [designs for the Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)  
- 🙋🏾🙋🏼 Questions? Visit the [Layer5 Discussion Forum](https://discuss.layer5.io) and join the [Layer5 Community Slack](http://slack.layer5.io)

**Comment by YashrajKupekar17** [comment]
I would like to solve this issue.Please assign .

**Comment by narasimha-1511** [comment]
Go on @YashrajKupekar17  🚀

**Comment by sudhanshutech** [comment]
@YashrajKupekar17 any progress?

**Comment by YashrajKupekar17** [comment]
yeah I have raised a new pr according to the changes discussed in the meeting .
https://github.com/layer5io/docs/pull/347
this is the link to the pr. check and please merge it
