### ISSUE TITLE
Broken hyperlink - embedding designs

### ISSUE THREAD

**Issue by leecalcote** [layer5io/docs#343]
#### Current Behavior
This section has a broken hyperlink - https://docs.layer5.io/meshmap/designer/export-designs/#exporting-as-embedding

#### Expected Behavior
Replace with new page location.

---

#### Contributor Guide and Resources
- 📚 [Instructions for contributing to documentation](https://github.com/layer5io/docs/blob/master/CONTRIBUTING.md)
   - Layer5 documentation [site](https://docs.layer5.io) and [source](https://github.com/layer5io/docs/)
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by kaushiktak19** [comment]
Hey @leecalcote, Can I work on this issue ? I have understood the task and am ready to get started.

**Comment by hargunkaur286** [comment]
@kaushiktak19 May I know if you have the website setup and working locally?

**Comment by kaushiktak19** [comment]
Hi @leecalcote and @hargunkaur286 ,

I've set up the documentation site locally and have addressed the broken hyperlink issue. I’ve verified the fix and created a video demonstrating the changes and how the link now correctly points to the updated page location.

Could you please review the video to ensure the fix aligns with what’s needed? If everything looks good, I’m ready to proceed with committing the changes and creating a pull request.

https://github.com/user-attachments/assets/b0afea9c-3408-4a81-9263-c4e87138e557


Also, could I be assigned this issue so I can track it more effectively?

**Comment by sudhanshutech** [comment]
Go ahead @kaushiktak19 . 
Please add also as a agenda item for today in website meet here: https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit so lets discuss this. Please join at 5:30pm IST

**Comment by kaushiktak19** [comment]
Sure @sudhanshutech, I will join the meet and will be raising a PR for this issue soon.

**Comment by kaushiktak19** [comment]
Hey @sudhanshutech @leecalcote @hargunkaur286, I have raised a PR for fixing this issue, do let me know if it is ready to go or something else is needed from my side.
