### ISSUE TITLE
[Docs] Deploying Designs

### ISSUE THREAD

**Issue by leecalcote** [layer5io/docs#344]
#### Current State
This page is missing content - https://docs.layer5.io/meshmap/tasks/designs/deploying-designs/

#### Desired State
[Mastering Meshery Learning Path](https://meshery.layer5.io/academy/learning-paths/mastering-meshery) content or Meshery Docs content can be reused (copied and pasted) here.

---

#### Contributor Guide and Resources
- 📚 [Instructions for contributing to documentation](https://github.com/layer5io/docs/blob/master/CONTRIBUTING.md)
   - Layer5 documentation [site](https://docs.layer5.io) and [source](https://github.com/layer5io/docs/)
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by sparshagl** [comment]
Hi @leecalcote, could I contribute to this as my first issue?

I'm just trying to get familiar with the community and have already set up a local development environment for the project.

In case there's already someone working on this, could you point me to other similar issues as a first-time contributor?

**Comment by leecalcote** [comment]
@sparshagl, sure. You might parlay with @Alero-Awani. 

@Alero-Awani, the clock is ticking.
