### ISSUE TITLE
[Docs] Working with Components

### ISSUE THREAD

**Issue by Alero-Awani** [layer5io/docs#354]
#### Current State
In the [MeshMap docs](https://docs.layer5.io/meshmap/)

"Working with Components" appears twice:

1. Under [Getting Started With Designs](https://docs.layer5.io/meshmap/getting-started/working-with-components/) and 
2. In the Main [Meshmap table of content](https://docs.layer5.io/meshmap/concepts/)

#### Desired State

There should only be one occurrence of the "Working with Components" document in the MeshMap docs, and it should be structured clearly to avoid confusing users. The content from both existing pages could be merged and expanded to accurately explain what components are and what they can do within MeshMap. 

This new document should factor in:

1. Configuring components.
2. Using the radial context menu to lock, style, duplicate, and delete components.
3. Annotations

More research should be done on the Use of components within Meshmap.

---

#### Contributor Guide and Resources
- 📚 [Instructions for contributing to documentation](https://github.com/layer5io/docs/blob/master/CONTRIBUTING.md)
   - Layer5 documentation [site](https://docs.layer5.io) and [source](https://github.com/layer5io/docs/)
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by sparshagl** [comment]
@Alero-Awani I can get started with merging the contents, followed by additional points. 

Where should we put the final doc?

**Comment by Alero-Awani** [comment]
For now it will be under "Getting Started with Designs"
