### ISSUE TITLE
Index website’s sitemap.xml

### ISSUE THREAD

**Issue by sudhanshutech** [layer5io/docs#364]
#### Current Behavior

website’s sitemap.xml was last indexed a year ago.

#### Expected Behavior

It need to be indexed again at current date

#### Environment

- **Host OS:** Mac Linux Windows
- **Browser:** Chrome Safari Firefox Edge Opera

---

#### Contributor Guide and Resources
- 📚 [Instructions for contributing to documentation](https://github.com/layer5io/docs/blob/master/CONTRIBUTING.md)
   - Layer5 documentation [site](https://docs.layer5.io) and [source](https://github.com/layer5io/docs/)
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
fixed in #367
