### ISSUE TITLE
[Docs] Writeup of Recognizing User and Contributor Milestones with Badges

### ISSUE THREAD

**Issue by leecalcote** [layer5io/docs#37]
:help-wanted: Help wanted in describing the recognition program --&gt; <https://docs.layer5.io/cloud/tutorials/assigning-user-badges/some> content from the blog post (<https://layer5.io/blog/community/layer5-recognition-program>) and handbook (<https://layer5.io/community/handbook/recognition>) an be regurgitated on this docs page.
:help-wanted:

[Slack Message](https://layer5io.slack.com/archives/C015QJKUMPU/p1698961196142789)

**Comment by vishalvivekm** [comment]
Will be making a call for volunteers for the ask here on Websites meeting November 6th, 2023 starting 8 AM central time.

**Comment by Savio629** [comment]
@vishalvivekm Would like to take up this issue..

**Comment by abhijeetgauravm** [comment]
There u go @Savio629
