### ISSUE TITLE
[Docs] Enable Site Search with Button Click

### ISSUE THREAD

**Issue by leecalcote** [layer5io/docs#373]
#### Current State
Clicking on the search button doesn't search the site.

#### Desired State
<img width="728" alt="Screenshot 2024-09-20 at 4 05 58 PM" src="https://github.com/user-attachments/assets/9c58689f-3301-4ecd-853a-e8e3cefac28f">

---

#### Contributor Guide and Resources
- 📚 [Instructions for contributing to documentation](https://github.com/layer5io/docs/blob/master/CONTRIBUTING.md)
   - Layer5 documentation [site](https://docs.layer5.io) and [source](https://github.com/layer5io/docs/)
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Pramodinikarlapudi** [comment]
Hey, I would love to contribute. I am building same features for my personal website.   I am new to contributing, where can I find the website?

**Comment by Pramodinikarlapudi** [comment]
Hey, I am working on it :)

**Comment by void-hr** [comment]
@Pramodinikarlapudi can you update the status, if you are not currently working on this issue, I would like to work on it. Else if you are facing any problem then we can solve it.

**Comment by void-hr** [comment]
@leecalcote as there is no current assignee can I take this one?
