### ISSUE TITLE
[Docs] Include steps to sign off commits

### ISSUE THREAD

**Issue by vishalvivekm** [layer5io/docs#374]
#### Current State
The [CONTRIBUTING-gitflow.md](https://github.com/layer5io/docs/blob/master/CONTRIBUTING-gitflow.md) file currently lacks instructions on how to sign off commits in order to meet the Developer Certificate of Origin (DCO) requirements.

#### Desired State
The guide should include steps for contributors to sign off their commits, following the DCO requirements.
The steps provided in the [Meshery CONTRIBUTING guide](https://docs.meshery.io/project/contributing#general-contribution-flow) can be used as a reference. 

For more details on DCO, see the [DCO](https://developercertificate.org/) file and how it works [here](https://github.com/probot/dco#how-it-works).

---

#### Contributor Guide and Resources
- 📚 [Instructions for contributing to documentation](https://github.com/layer5io/docs/blob/master/CONTRIBUTING.md)
   - Layer5 documentation [site](https://docs.layer5.io) and [source](https://github.com/layer5io/docs/)
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by csengineer1990** [comment]
Hi, I’m new here and would like to work on this issue. With your help, I believe I can solve it. Could you please assign this task to me?
Thank you!

**Comment by vishalvivekm** [comment]
> Hi, I’m new here and would like to work on this issue. With your help, I believe I can solve it. Could you please assign this task to me? Thank you!

Hi @csengineer1990 
Thank you for chiming in.
Please refer to the links in the issue description and let me know if you need any help.
Assigning! Happy contributions 🎉
