### ISSUE TITLE
[Subscription Tiers] Relocate and resize

### ISSUE THREAD

**Issue by leecalcote** [layer5io/docs#406]
#### Mockups

<img width="992" alt="Screenshot 2024-10-31 at 10 08 08 PM" src="https://github.com/user-attachments/assets/457d872a-148d-4cb0-bfc7-f25f6c1395ff">

---

#### Contributor Guide and Resources
- 📚 [Instructions for contributing to documentation](https://github.com/layer5io/docs/blob/master/CONTRIBUTING.md)
   - Layer5 documentation [site](https://docs.layer5.io) and [source](https://github.com/layer5io/docs/)
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@vishalvivekm or @SAHU-01, please carry forward with this.

**Comment by ayush14189** [comment]
@leecalcote if it is still open, can I take up this issue?

**Comment by leecalcote** [comment]
Yes, the issue is still open. It gives me pause to assign the issue to you, though, if you can’t tell that the issue remains unresolved on the site.

**Comment by SAHU-01** [comment]
I'll take this up @leecalcote and fix this ASAP!

**Comment by leecalcote** [comment]
Thank you
