### ISSUE TITLE
[Docs] Images are displayed too large

### ISSUE THREAD

**Issue by fitzergerald** [layer5io/docs#410]
#### Current State
Image size is out of control on some of the pages, like https://docs.layer5.io/kanvas/concepts/relationships/
<img width="1400" alt="Screenshot 2024-11-08 at 12 52 27 PM" src="https://github.com/user-attachments/assets/39023168-7632-4343-8be2-315bab2793a1">

#### Desired State

Show a thumbnail. 

Allow visitors to click on the thumbnail to view a larger size, if they want to.

---

#### Contributor Guide and Resources
- 📚 [Instructions for contributing to documentation](https://github.com/layer5io/docs/blob/master/CONTRIBUTING.md)
   - Layer5 documentation [site](https://docs.layer5.io) and [source](https://github.com/layer5io/docs/)
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Thank you, @fitzergerald. This this a good request.

**Comment by Ravnoor12** [comment]
Hello @leecalcote , I wanted to complete this task. can you assign this issue to me. thanks

**Comment by leecalcote** [comment]
@Ravnoor12 thanks for working on this. Please keep pushing forward.

In the meantime, more help is wanted.
