### ISSUE TITLE
[Build] Remove the warning shown during site build for taxonomyterm

### ISSUE THREAD

**Issue by aakankshabhende** [layer5io/docs#425]
#### Current State
When executing make site, the following log is shown in terminal output.

`WARN  DEPRECATED: Kind "taxonomyterm" used in outputs configuration is deprecated, use "taxonomy" instead.
`
#### Desired State
No build warnings.

**Comment by shivankurchavan** [comment]
looks like the `taxonomyTerm` is changed to `term`
