### ISSUE TITLE
Convert Meshery Architecture Slides to SVG for Documentation

### ISSUE THREAD

**Issue by iArchitSharma** [layer5io/docs#43]
We're looking for assistance in converting the Meshery Architecture slides to SVG format and incorporating them into our documentation. Here are the details:

### Task

- Visit the Meshery Architecture slides.
- Download ~1/2 of the slides to SVG format.
- Upload the SVG slides to a relevant page on our documentation site.

### Challenges
You might encounter a few technical hurdles along the way:

1. Too many / too large rasterized images: Be mindful of the number and size of rasterized images embedded in the SVG files.
2. Not curating the SVG or the slide for presentation in docs: The slides may require some editing and formatting to ensure they display effectively within our documentation. You can see an example of a well-curated slide [here](https://docs.layer5.io/cloud/security/roles/).
**Here is what the slide looks like for above example:**
![Provider Admin image](https://github.com/layer5io/docs/assets/74408634/a50fbc1d-d298-43a8-86af-6652bc2b1c65)

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by ksauravhash** [comment]
I would like to help but I don't know the process. I'd be helpful if you would tell the process too.

**Comment by ksauravhash** [comment]
It seems that the task has already been done.

**Comment by abhijeetgauravm** [comment]
> It seems that the task has already been done.

// @iArchitSharma

**Comment by leecalcote** [comment]
@iArchitSharma confirm with @dragon-slayer875 that this is complete, please.

**Comment by Ashparshp** [comment]
@dragon-slayer875 ??

**Comment by dragon-slayer875** [comment]
> @dragon-slayer875 ??

Yes this is complete for all the roles that we currently have. We will be deleting a few of them soon and will be updating accordingly.
