### ISSUE TITLE
Incorrect Twitter Link

### ISSUE THREAD

**Issue by hemantmm** [layer5io/docs#44]
#### Current Behavior

The Twitter link does not redirect to the Layer5 Twitter page

#### Expected Behavior

Change the Twitter link to open [https://twitter.com/layer5](url) instead

#### Screenshots/Logs

![Screenshot 2023-11-04 120205](https://github.com/layer5io/docs/assets/92446645/f789f117-7a00-4bd6-98e9-2c50e353c850)

**Comment by hemantmm** [comment]
Would like to work on this.

**Comment by 35C4n0r** [comment]
This issue will be fixed in https://github.com/layer5io/docs/issues/15
