### ISSUE TITLE
Add Meshery Docs link in the footer

### ISSUE THREAD

**Issue by iArchitSharma** [layer5io/docs#51]
#### Current Behavior
![image](https://github.com/layer5io/docs/assets/74408634/a6a17201-7cd2-4255-bb30-146e2870961b)

#### Desired Behavior
Add Meshery Docs link in the footer
---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

**Comment by hemantmm** [comment]
@iArchitSharma would like to work on this issue.

**Comment by iArchitSharma** [comment]
@hemantmm go on, remember you have to wait till this [PR](https://github.com/layer5io/docs/pull/46) is merged

**Comment by iArchitSharma** [comment]
@hemantmm you can start working on it now!

**Comment by hemantmm** [comment]
@iArchitSharma is this the link [https://docs.meshery.io/](url) for meshery docs?

**Comment by iArchitSharma** [comment]
@hemantmm Yes it is

**Comment by hemantmm** [comment]
@iArchitSharma in which section the Docs link should be added?

**Comment by iArchitSharma** [comment]
> @iArchitSharma in which section the Docs link should be added?

Solutions section

**Comment by hemantmm** [comment]
@iArchitSharma the title should be Meshery Docs?
And should it be at top?

**Comment by iArchitSharma** [comment]
> @iArchitSharma the title should be Meshery Docs? And should it be at the top before MeshMap?

yes "Meshery Docs" and keep it at top
