### ISSUE TITLE
typo in catalog page

### ISSUE THREAD

**Issue by abhijeetgauravm** [layer5io/docs#52]
#### Current State
![22735707-d2dd-4717-a064-d2f45c57919a](https://github.com/layer5io/docs/assets/65087356/f526ad0e-fd15-4949-9c03-2e02fa05b484)
There is typo [here](https://deploy-preview-46--bejewelled-pegasus-b0ce81.netlify.app/cloud/catalog/) 'thaat' , 'caan' , 'alwaays' and 'praactices'

#### Desired State
'that' , 'can' , 'always' , 'practices'
---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by hemantmm** [comment]
@abhijeetgauravm would like to work on this issue.
