### ISSUE TITLE
Adding MeshMap keyboard shortcuts in the MeshMap docs.

### ISSUE THREAD

**Issue by Modern-artist** [layer5io/docs#55]
### Current Behavior
Currently, we don't have MeshMap keyboard shortcuts in the MeshMap docs.

### Desired Behavior
We have to add the MeshMap keyboard shortcuts in the MeshMap docs.

### location in meshmap of keyboard shortcuts.
<img width="1433" alt="Screenshot 2023-11-11 at 12 21 04 AM" src="https://github.com/layer5io/docs/assets/90668597/a30d0193-350d-4dc6-8215-737f0c105fd5">

<img width="1440" alt="Screenshot 2023-11-11 at 12 20 13 AM" src="https://github.com/layer5io/docs/assets/90668597/7e0809de-5447-45e9-ad9a-bedb1d5bc1d5">

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

**Comment by leecalcote** [comment]
Adding missing "help wanted" and "good first issue" labels.

**Comment by vaibhavpnimkar** [comment]
I would like to work on this issue

**Comment by vaibhavpnimkar** [comment]
@abhijeetgauravm  i am facing a issue in setting up local env(
![Screenshot from 2023-11-11 19-36-17](https://github.com/layer5io/docs/assets/128807866/b81cd29b-03d7-4919-8a74-bd1f02cc4a3c). May be docker target is missing in Makefile either cause i have docker installed and i have followed steps in contributing guidelines
