### ISSUE TITLE
Duplicate Meta Descriptions

### ISSUE THREAD

**Issue by iArchitSharma** [layer5io/docs#63]
#### Current Behavior
All the pages in docs.layer5.io has same meta description which make it difficult for search engines and users to differentiate between different webpages.
![image](https://github.com/layer5io/docs/assets/74408634/490fd7d7-6dbf-421b-aa3b-cea5761986b8)

#### Expected Behavior
Add a unique, relevant meta description for each webpage.

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by hemantmm** [comment]
@iArchitSharma would like to work on this issue.

**Comment by iArchitSharma** [comment]
sure!

> @iArchitSharma would like to work on this issue.

**Comment by iArchitSharma** [comment]
sure!

> @iArchitSharma would like to work on this issue.

**Comment by iArchitSharma** [comment]
how's the progress?

**Comment by hemantmm** [comment]
Was busy with some other work will start working on it by today or tomorrow.

**Comment by leecalcote** [comment]
Final check-in, @hemantmm. Are you still committed to seeing this through?

**Comment by hemantmm** [comment]
Sorry, @leecalcote I was not feeling well due to which I was not able to contribute.

**Comment by iArchitSharma** [comment]
@hemantmm  No problem then, should i take over this issue or you still intrested

**Comment by hemantmm** [comment]
@iArchitSharma you may take up this issue.
