### ISSUE TITLE
Misspelled Visualizer category

### ISSUE THREAD

**Issue by leecalcote** [layer5io/docs#64]
<img width="604" alt="Screenshot 2023-11-15 at 1 55 21 PM" src="https://github.com/layer5io/docs/assets/7570704/932c6c5b-062d-49dd-87a5-0e7446494e94">

**Comment by balagowda** [comment]
@leecalcote i would like to work on this

**Comment by phukon** [comment]
Could you please assign the fix to me @leecalcote ?

**Comment by leecalcote** [comment]
Thanks!
