### ISSUE TITLE
[Feature] Add hotkey to site search field

### ISSUE THREAD

**Issue by leecalcote** [layer5io/docs#66]
#### Current Behavior
The docs site has sitewide search, but no hotkey to access it.

#### Desired Behavior
1. On press of either `/`, assign focus to site search field.

#### Implementation
....

#### Acceptance Tests
1. either hotkey combination works.
1. `/` in shown in search field.

#### Mockups
<img width="259" alt="Screenshot 2023-11-15 at 3 03 28 PM" src="https://github.com/layer5io/docs/assets/7570704/1f8e3793-12ac-40f7-b071-476e57f652cd">

_## Future:_

_Add support for a full command bar with `⌘/CTL+K`._

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

**Comment by vaibhavpnimkar** [comment]
hey @leecalcote i would like to work on this!!

**Comment by phukon** [comment]
Could you please assign the to me @leecalcote ?

**Comment by ankushbhardwaj408** [comment]
Thanks for volunteering guys. Assigning in chronological order. @phukon Here you'll find many good-first and help-wanted issues:
https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+org%3Ameshery+org%3Aservice-mesh-performance+org%3Aservice-mesh-patterns+label%3A%22help+wanted%22+

Feel free to check these out and comment to get assigned.

**Comment by vaibhavpnimkar** [comment]
thankyou @ankushbhardwaj408 for assigning this issue to me but in mean time i have been assigned to a new issue so @phukon can take this issue !

**Comment by ankushbhardwaj408** [comment]
there you go @phukon

**Comment by ankushbhardwaj408** [comment]
Closed via- #79

**Comment by leecalcote** [comment]
Thank you
