### ISSUE TITLE
[Docs] Landing Page: Use all flex layout, not grid layout

### ISSUE THREAD

**Issue by leecalcote** [layer5io/docs#76]
#### Current State
The homepage (aka the landing page) of this doc site has a mixture of two different types of container layouts.

#### Desired State

1. Ideally, only flex layout is used.
2. Rearrange the layout slightly (see mockup).

<img width="1471" alt="Screenshot 2023-11-17 at 1 47 20 PM 1" src="https://github.com/layer5io/docs/assets/7570704/18fedb1f-371d-45f7-a9ea-452c5ba484ea">

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by ankushbhardwaj408** [comment]
i would like to work on this.

**Comment by trinayreddy4** [comment]
@leecalcote i would like to work on this..

**Comment by leecalcote** [comment]
Sounds great. Thank you, @trinayreddy4

**Comment by leecalcote** [comment]
@trinayreddy4 any progress to report?

**Comment by trinayreddy4** [comment]
yeah i would be raising the PR soon....

**Comment by leecalcote** [comment]
@trinayreddy4 final check-in. Are you still committed to this assignment?

**Comment by SamIsTheFBI** [comment]
Hi, I'd like to work on this issue.

@leecalcote if nobody is working on it can you assign it to me?

**Comment by leecalcote** [comment]
Thanks, @SamIsTheFBI
