### ISSUE TITLE
[Docs] New Page: "Getting Started - Creating a Design from Scratch"

### ISSUE THREAD

**Issue by leecalcote** [layer5io/docs#77]
#### Current State
A new docs page is needed to describe this process to users, who create a design from a blank canvas.

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by vaibhavpnimkar** [comment]
i would to like to work on this!

**Comment by vaibhavpnimkar** [comment]
hey @abhijeetgauravm  do i have to create docs only designer or visualizer and designer both?

**Comment by vaibhavpnimkar** [comment]
hey i have fixed two issues in pr plz have a look
issue #57 and this #97
