### ISSUE TITLE
[Docs] Navigation Menu for Mobile Visitors

### ISSUE THREAD

**Issue by leecalcote** [layer5io/docs#82]
#### Current State
There is no navigation menu for mobile visitors.

#### Desired State
Implement a mobile navigation menu in accoradance with the mockup below.

![docs layer5 io](https://github.com/layer5io/docs/assets/7570704/da75c7e5-aaf3-4e5f-8f51-5a726ac340e5)

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by mad-max-fury** [comment]
Hello @leecalcote, I am interested in working on this issue. can you assign me to it

**Comment by leecalcote** [comment]
Sounds great. Thanks, @mad-max-fury 👍

**Comment by abhijeetgauravm** [comment]
@mad-max-fury updates here?

**Comment by Ashparshp** [comment]
The issue it already been completed, so closing it now!
