### ISSUE TITLE
[Docs] Fullscreen image modal support for `<img>` images

### ISSUE THREAD

**Issue by coder12git** [layer5io/docs#85]
#### Desired Behavior
 - Adding Shortcode support for related topics - [check here](https://layer5io.slack.com/archives/CFGG6U10E/p1700227097395789?thread_ts=1700226835.513289&cid=CFGG6U10E)
- Turning message into shortcodes for reuse - [check here](https://layer5io.slack.com/archives/CFGG6U10E/p1700227480866189?thread_ts=1700226835.513289&cid=CFGG6U10E)
- Enhance current image modal, to support html img tag ( currently, you can use this feature using this syntax - `![alt](/img.svg)`

#### Mockups

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

**Comment by coder12git** [comment]
@leecalcote please add your items or any other features, if missing here.

**Comment by leecalcote** [comment]
Heads-up: the Slack messages are I’ll expire from view at some point.

**Comment by leecalcote** [comment]
Oh, I see that @coder12git is assigned. Never mind. She works expeditiously, so no need to bother persisting the Slack messages.

**Comment by Lucif3r-in** [comment]
Has this issue been resolved @coder12git?
Please elaborate the issue as the links are redirecting to slack

**Comment by leecalcote** [comment]
Yes, @Lucif3r-in, there is an open need to support HTML `img` tags, not just markdown `![]` tags.

**Comment by horizenight** [comment]
Hello @leecalcote 
I saw this unassigned and unresolved. 
The current `hugo` setup allows the use of the HTML `img` tag , so both the `img` and `![]` tags. works.

Test: 
 Tested the markdown code available in cloud `_index.md` 
 
<img width="1165" alt="image" src="https://github.com/layer5io/docs/assets/76839614/4dc3aa6b-2e14-43c0-aed1-afd4d5fd1b21">

Result: 
<img width="1460" alt="image" src="https://github.com/layer5io/docs/assets/76839614/b5af693a-1427-40ce-aab3-4ddc4f6717bf">

Conclusion : 
This issue can be termed as resolved.

**Comment by leecalcote** [comment]
@horizenight, the need here is to support the full screen modal behavior on click of an image encoded by the HTML `<img>` tag and not just for images encoded by the `![]` markdown tag. Pay particular attention to what happens on click of an image and the difference between these two.
