### ISSUE TITLE
[Docs] - Add Getting start with designs Page

### ISSUE THREAD

**Issue by coder12git** [layer5io/docs#86]
#### Current Behavior

https://docs.layer5.io/meshmap/getting-started/starting-scratch/
#### Mockups

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

**Comment by Raj100679** [comment]
@coder12git Is there anything here to work on?
