### ISSUE TITLE
Create a "Who Can Use This Feature" layout/block/shortcode

### ISSUE THREAD

**Issue by leecalcote** [layer5io/docs#89]
#### Current Behavior
Some features of Cloud and MeshMap are available to all users, while other features are available only at specific subscription levels.

#### Desired Behavior
Use frontmatter designations to drive a notice at the top of the page for which subscription plan this feature is applicable.

#### Implementation
Each docs page should be capable of having frontmatter like:

```
plan: free, team, enterprise
```

#### Acceptance Tests
Every page has a callout for subscription applicability.

#### Mockups
[Examples from Figma docs](https://help.figma.com/hc/en-us/articles/360039825314-Guide-to-comments-in-Figma) - 
<img width="700" alt="Screenshot 2023-11-21 at 4 05 39 PM" src="https://github.com/layer5io/docs/assets/7570704/4ee5f553-cb3a-4fe5-97d5-eae101377149">

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

**Comment by horizenight** [comment]
Hello @leecalcote 
would like to work on this.

**Comment by psankhe28** [comment]
Hi @leecalcote , can you please provide more details regarding this? Do we need to create the UI in figma or code it?

**Comment by SAHU-01** [comment]
@leecalcote is this issue up for grab? If yes, may I work on it?

**Comment by Ashparshp** [comment]
@SAHU-01 You're still up for this?

**Comment by SAHU-01** [comment]
Yes!

**Comment by SAHU-01** [comment]
@leecalcote , @Ashparshp is there a list available for the subscription-only feature of Cloud and Meshmap? or should I create a list first , get it approved then add the frontmatter accordingly?

**Comment by Ashparshp** [comment]
@SAHU-01 https://layer5.io/pricing

More on this @leecalcote will share if needed. Please check if it's helpful..
